### ISSUE TITLE
No update from Upstream behind proxy

### ISSUE THREAD

**Issue by erSitzt** [inverse-inc/fingerbank#16]
Fingerbank does not work behind a proxy.
I needed to install LWP::Protocol::https and use one of these lines to configure the proxy.

    $ua = new LWP::UserAgent(ssl_opts => { verify_hostname => 0 });
    $ua->env_proxy (if the system has the proxy set via environment variable)

or

    $ua = new LWP::UserAgent(ssl_opts => { verify_hostname => 0 });
    $ua->proxy(['https', 'http', 'ftp'] => "http://proxy.expert.de:8080");
    $ua->protocols_allowed([ 'https', 'http', 'ftp' ]);

I think there should be an option in Fingerbank / Packetfence to set the proxy from the admin interface.
I needed to change `/usr/local/fingerbank/lib/fingerbank/DB.pm` and `/usr/local/fingerbank/lib/fingerbank/Query.pm`

Packetfence v5.1

**Comment by dwlfrth** [comment]
I'll have a look at what should be the best implementation for that kind of use case. Thanks for reporting

**Comment by julsemaan** [comment]
This seems like it should be part of our next version and it seems pretty easy to add

**Comment by julsemaan** [comment]
I will move the issue to the new perl client repo
