### ISSUE TITLE
duplicate os id: 249 [os 111] 

### ISSUE THREAD

**Issue by eneq123** [inverse-inc/fingerbank#18]
subj

**Comment by julsemaan** [comment]
One is Linux/Knoppix/, the other is Routers and APs/Zioncom Wireless Router/

Not sure what the duplication is..

**Comment by eneq123** [comment]
I mean: line 240: [os 111] and line 249: [os 111]

**Comment by dwlfrth** [comment]
Is this still accurate since it uses the old flat-files ?

**Comment by dwlfrth** [comment]
Closing this issue since it relates to old flat-files
