### ISSUE TITLE
perl library logs not rotated

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/fingerbank#21]
Need to install logrotate job on installation time.

/etc/logrotate.d/fingerbank
```
# logrotate file for fingerbank

/usr/local/fingerbank/logs/*log {
    weekly
    rotate 4
    missingok
    compress
    create 660 fingerbank fingerbank
    copytruncate
}
```

**Comment by fdurand** [comment]
Debian version:
# logrotate file for fingerbank

/usr/local/fingerbank/logs/*log {
    su fingerbank fingerbank
    weekly
    rotate 4
    missingok
    compress
    create 660 fingerbank fingerbank
    copytruncate
}

**Comment by julsemaan** [comment]
To be honnest, I think we should put it to daily rotate 1 because on big setups it can do almost 1G per day....

**Comment by extrafu** [comment]
Indeed. I would rotate daily and keep 2 logs max. So 1 active, 2 rotated.

**Comment by julsemaan** [comment]
@lzammit what are you doing on @extrafu account ?

**Comment by dwlfrth** [comment]
I modified the log level so 1 week should be ok :)

**Comment by julsemaan** [comment]
In the code or in the conf ?
